plugins {
    id 'fabric-loom' version "1.6-SNAPSHOT"
    id 'maven-publish'
}

version = project.version
group = project.group

repositories {
    mavenCentral()
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    // Репозиторий для owo-lib
    maven { url "https://maven.wispforest.io" }
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "conquest-hud" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modImplementation files("libs/cardinal-components-base-5.2.2.jar")
    modImplementation files("libs/cardinal-components-entity-5.2.2.jar")

    modImplementation "maven.modrinth:trinkets:3.7.1"
    modApi "maven.modrinth:cloth-config:11.1.118+fabric"
    modImplementation "maven.modrinth:modmenu:7.2.2"

    implementation "org.lwjgl:lwjgl-nanovg:${project.lwjgl_version}"
    implementation "org.lwjgl:lwjgl-nanovg:${project.lwjgl_version}:natives-windows"

    // Интеграция строгой сетевой синхронизации
    modImplementation "maven.modrinth:owo-lib:${project.owo_version}"
    annotationProcessor "maven.modrinth:owo-lib:${project.owo_version}"

    // Ручное добавление парсера Jankson (зависимость owo-lib)
    implementation "blue.endless:jankson:1.2.3"
}

processResources {
    def version_property = project.version
    inputs.property "version", version_property
    filesMatching("fabric.mod.json") {
        expand "version": version_property
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}